service: mutantpen

provider:
  name: aws
  runtime: nodejs8.10
  profile: ${self:custom.secrets.AWS_PROFILE}
  stage: ${self:custom.secrets.NODE_ENV}
  region: us-west-1
  environment:
    NODE_ENV: ${self:custom.secrets.NODE_ENV}

functions:
  nuxt:
    handler: index.nuxt
    events:
      - http: ANY /
      - http: ANY /{proxy+}
  convert:
    handler: lambdas/convert.handler
    description: File Converter
    name: convert__${self:custom.secrets.NODE_ENV}

plugins:
  - serverless-apigw-binary
  - serverless-domain-manager

custom:
  secrets: ${file(secrets.json)}
  apigwBinary:
    types:
      - '*/*'
  customDomain:
    domainName: ${self:custom.secrets.DOMAIN}
    basePath: ''
    stage: ${self:custom.secrets.NODE_ENV}
    createRoute53Record: true
    enabled: false